FROM python:3.12-slim

WORKDIR /mlflow

ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    mlflow==3.3.2 \
    psycopg2-binary

RUN mkdir -p /mlflow/artifacts

EXPOSE 5000
