FROM python:3.12-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir \
    mlflow==3.3.2 \
    psycopg2-binary

RUN mkdir -p /mlflow/artifacts

EXPOSE 5000

CMD ["mlflow","server","--host","0.0.0.0","--port","5000","--backend-store-uri","postgresql+psycopg2://mlflow:mlflow@postgres:5432/mlflow","--default-artifact-root","/mlflow/artifacts"]