mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "final-model-v2"
  registered_model_name: "credit-risk-model"
  alias: "champion"

  artifacts:
    selected_features: "model_contract/selected_features.json"
    signature: "model_contract/signature.json"
    input_example: "examples/input_example.csv"
    output_example: "examples/output_example.csv"

  tags:
    project: "credit-risk"
    team: "data-science"
    problem_type: "binary-classification"
